version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ./back-end/node-project
      dockerfile: dockerfile
    ports:
      - "3300:3300"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/database"
    volumes:
      - ./back-end/node-project:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: always

  angular-frontend:
    build:
      context: ./front-end/angular-project
      dockerfile: dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: always

  nextjs-frontend:
    build:
      context: ./front-end/next-project
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: