version: "3.8"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: dockerfile
    ports:
      - "3300:3300"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/database"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./projeto-inovanti
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./projeto-inovanti:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: